config/routes.rb
Rails.application.routes.draw do
  resources :attendees
  resources :locations
  resources :meetings
  resources :sponsors
  resources :events

  root 'events#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Campusevents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Campus Events</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to("Events", events_path)%></li>
              <li><%= link_to("Attendees", attendees_path)%></li>
              <li><%= link_to("Meetings", meetings_path)%></li>
              <li><%= link_to("Locations", locations_path)%></li>
              <li><%= link_to("Sponsors", sponsors_path)%></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </nav>


<div class="container">
  <div class="row">

      <div class="col-lg-8">
        <%= yield %>
      </div>

      <div class="col-lg-4">
        <%= yield :sidebar%>

      </div>

  </div>
</div>

</body>
</html>